@startuml
!theme vibrant
hide footbox

skinparam roundcorner 10
skinparam BorderColor #1F2555
skinparam ArrowColor #A70100
skinparam classBackgroundColor #ffffff/5C6ACC
skinparam SequenceStereotypeFontColor #5C6ACC

skinparam SequenceGroup {
    BackgroundColor #ffffff/A9DCDF
}
skinparam participant {
    BackgroundColor #ffffff
    BorderColor #ffffff
}
@enduml
