@startuml
!theme vibrant

skinparam roundcorner 10

skinparam BorderColor #1F2555
skinparam ArrowColor #A70100
skinparam Shadowing true

skinparam SequenceGroup {
    BackgroundColor #ffffff/A9DCDF
}

skinparam participant {
    BackgroundColor #ffffff
    BorderColor #ffffff
    FontColor black
    FontName Consolas
}

skinparam note {
    BorderColor #D6B656
    BackgroundColor #FFF2CC
    StereotypeFontColor #5C6ACC
}

skinparam LegendBorderThickness 0
skinparam LegendBorderColor #ffffff

' common changes
autonumber
skinparam MaxMessageSize 120
hide footbox

@enduml
